### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by speleo3**

### CODE REVIEW

**Comment by jdhoek** [comment]
Added, thank you. Is Inkscape switching to Python 3 for its extensions?

**Comment by speleo3** [comment]
Yes, Inkscape is switching to Python 3.

**Comment by wstaelens** [comment]
Is the extension available in both inkscape (desktop app) AND inkscape (windows store app) ?

**Comment by jdhoek** [comment]
@wstaelens I would expect that you can install extensions in any Inkscape installation, regardless of its installation source. This extension should work in any recent Inkscape release.

See [the Inkscape documentation](https://inkscape.org/gallery/=extension/) for more information. I don't have access to Windows myself, so I can't confirm.

**Comment by wstaelens** [comment]
see other ticket, only get it working in one version of inkscape.

**Pull request closed without merging**
